//
// Created by maiso on 23/01/2024.
//

#ifndef PROJET_CONSTANTS_H
#define PROJET_CONSTANTS_H

// PROGRAM MODES
#define DEBUG_MODE 1                // Values : 0|1 - Will be interpreted as boolean. Displays additional infos on the standard output.
#define LOG_TO_FILE 1               // Values : 0|1 - Will be interpreted as boolean. Will print the results of the tests inside a .txt file.

// CRITICAL THREAD VALUES (for the Eval Tests). 
// Since it's heavy in computing, we allowed for a threaded version.
#define ALLOCATED_CORES 30          // Number of cores allocated for the eval tests.

// PROGRAM VALUES
#define RANDOM_NUMBERS_SIZE 1024    // The size of the random numbers generated by the program (in bits). DEFAULT : 2048
#define ITERATION_NUMBER 10000      // The number of iterations that must be made for the EXPMOD and DECOMP tests. DEFAULT : 10000
#define MILLER_RABIN_ITERATIONS 20  // Value of the cpt variable for the Miller Rabin test. DEFAULT : 20
#define RANDOM_SEED 2161324573      // The seed for the random number generator. Can be whatever you want as long as it can be saved as unsigned long. DEFAULT : 2161324573

#endif //PROJET_CONSTANTS_H
